name: Generate GitHub Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily
  workflow_dispatch: # Allow manual runs

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: VidAbw
          outputs: output/github-contribution-grid-snake.svg output/github-contribution-grid-snake-dark.svg

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Update snake"
          git push
